name: list_contatos_foto_dio
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.3

  image_picker: ^1.0.4
  path_provider: ^2.1.1
  mobx: ^2.2.1
  flutter_mobx: ^2.1.0+1
  firebase_auth: ^4.11.1
  firebase_core: ^2.19.0
  jsonwebtoken_decode: ^1.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  mobx_codegen:   

  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env


  uses-material-design: true